[package]
name = "voxel-renderer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
env_logger = "0.11.7"
glam = "0.30.0"
log = "0.4.26"
pollster = "0.4.0"
simple-wgpu = "0.3.0"
wgpu = "24.0.1"
wgpu-types = "24.0.0"
winit = "0.30"
